### PR TITLE
Move additional param required with JDK8 for javadoc generation

### PR DESCRIPTION
**Pull request by MichaelF25**
I've accidentally broke the CI build with JDK7 since I am working on JDK8.
With this PR, the build should work on both JDKs :-)

### CODE REVIEW

**Comment by michael-schnell** [comment]
I'll check if I can remove the JavaDoc errors instead of making the build depending on a JDK version. I had the same problems with other projects because of the incompatible JDK 8 change. See http://blog.joda.org/2014/02/turning-off-doclint-in-jdk-8-javadoc.html

**Comment by MichaelF25** [comment]
Updated the pull request using java5 annotations instead of the mojo javadoc tags

**Comment by michael-schnell** [comment]
Great - I will check it on the weekend.

**Comment by michael-schnell** [comment]
CAUTION: I changed the parameter name to "post-start-command". I guess you need to update your configuration, I will create a new Maven Central version if everything works for you. Just give mee a short feedback.

**Pull request merged**
